import '../../models/release_governance/release_approval.dart';
import '../../models/release_governance/release_governance_enums.dart';
import '../../models/release_governance/release_governance_policy.dart';
import '../../models/release_governance/release_governance_rule_value.dart';
import '../../models/release_governance/release_waiver.dart';

/// Default evidence requirement for release governance rules.
const ReleaseGovernanceEvidenceRequirement
    kReleaseGovernanceEvidenceRequirement =
    ReleaseGovernanceEvidenceRequirement(
  requireSourceReference: true,
  requireFingerprint: true,
  minimumEvidenceCount: 1,
);

/// Candidate release governance policy v1.
class ReleaseGovernancePolicyV1 {
  const ReleaseGovernancePolicyV1._();

  static const policyId = 'release-governance-v1';

  static ReleaseGovernancePolicy create() {
    final rules = _rules();
    return ReleaseGovernancePolicy(
      metadata: const ReleaseGovernancePolicyMetadata(
        policyId: policyId,
        policyVersion: 1,
        displayName: 'MasterPalm Release Governance',
        description:
            'Candidate release governance policy authorizing release progression based on Quality Gate snapshots, approvals and waivers.',
        owner: 'MasterPalm Engineering Governance',
        status: ReleaseGovernancePolicyStatus.candidate,
        schemaVersion: ReleaseGovernancePolicy.currentSchemaVersion,
        calculationVersion: ReleaseGovernancePolicy.currentCalculationVersion,
        canonicalizationVersion:
            ReleaseGovernancePolicy.currentCanonicalizationVersion,
        createdAt: '2026-01-01T00:00:00.000Z',
        rationale:
            'Conservative candidate policy governing standard releases without external CI/CD integration. Release Governance authorizes progression; it does not recalculate technical evidence.',
        changelog: [
          ReleaseGovernancePolicyChangelogEntry(
            version: 1,
            summary: 'Initial candidate release governance policy',
            author: 'MasterPalm Engineering Governance',
            createdAt: '2026-01-01T00:00:00.000Z',
          ),
        ],
        tags: ['release-governance', 'candidate'],
      ),
      governance: const ReleaseGovernanceGovernance(
        policyOwner: 'MasterPalm Engineering Governance',
        approvalAuthority: 'MasterPalm Engineering Governance',
        policyApprovalStatus: 'candidate',
        versioningStrategy: 'immutable-version-on-normative-change',
        rollbackPolicy: 'explicit-version-selection-only',
        emergencyPolicy: 'emergency-approval-with-mandatory-follow-up',
        waiverPolicy: 'explicit-limited-temporary-waivers-only',
        evidenceRequirements:
            'quality-gate-reference-approval-waiver-evidence-with-fingerprints',
        compatibilityRequirements:
            'explicit-compatibility-check-before-evaluation',
        retentionRequirements: 'policy-id-version-fingerprints-preserved',
        reviewCadence: 'quarterly',
        escalationAuthority: 'MasterPalm Engineering Governance',
        releaseApprovalAuthority: 'Release Manager Board',
        waiverGrantAuthority: 'Release Manager + designated waiver authority',
      ),
      rules: rules,
      ruleSets: _ruleSets(),
      approvalRequirements: _approvalRequirements(),
      waiverRules: _waiverPolicy(),
      decisionPolicy: const ReleaseGovernanceDecisionPolicy(
        requiredFailuresReject: true,
        blockingFailuresReject: true,
        criticalFailuresReject: true,
        optionalFailuresCreateConditions: false,
        missingApprovalsCreatePending: true,
        rejectedApprovalRejects: true,
        expiredApprovalCreatesPending: true,
        validWaiverMayCreateConditionalApproval: true,
        warningMayCreateCondition: true,
        partialCompatibilityAllowed: false,
        partialEligibilityAllowed: false,
        minimumRuleCoverage: 100,
        minimumApprovalCoverage: 100,
        minimumEvidenceCoverage: 100,
        qualityGateAcceptedDecisions: ['passed'],
        qualityGateConditionalDecisions: ['partial'],
        qualityGateRejectedDecisions: [
          'failed',
          'unavailable',
          'incompatible',
          'error',
        ],
        allowEmergencyOverride: false,
        allowHistoricalEvaluation: false,
        allowRetiredPolicyForHistoricalEvaluation: false,
      ),
      evidencePolicy: const ReleaseGovernanceEvidencePolicy(
        requireQualityGateFingerprint: true,
        requireQualityGateSnapshotId: true,
        requireApprovalEvidence: true,
        requireAuthorityEvidence: true,
        requireWaiverEvidence: true,
        requireCompensatingControlEvidence: true,
        requireReleaseArtifactReferences: false,
        requireCommitId: true,
        requireProjectId: true,
        requirePolicyFingerprint: true,
        minimumEvidenceCoverage: 100,
        allowDerivedEvidence: false,
        allowContextualEvidence: true,
      ),
      compatibilityPolicy: ReleaseGovernanceCompatibilityPolicy(
        allowedQualityGatePolicyIds: const ['quality-gate-release-v1'],
        allowedQualityGatePolicyVersions: const [1],
      ),
      eligibilityPolicy: const ReleaseGovernanceEligibilityPolicy(
        requireQualityGate: true,
        requireReleaseContext: true,
        requireApprovalsForEvaluation: true,
        allowCandidatePolicy: true,
      ),
      supportedReleaseTypes: const [
        ReleaseType.development,
        ReleaseType.internal,
        ReleaseType.beta,
        ReleaseType.releaseCandidate,
        ReleaseType.production,
        ReleaseType.hotfix,
        ReleaseType.rollback,
        ReleaseType.emergency,
      ],
      supportedEnvironments: const [
        ReleaseEnvironment.development,
        ReleaseEnvironment.test,
        ReleaseEnvironment.qa,
        ReleaseEnvironment.staging,
        ReleaseEnvironment.preProduction,
        ReleaseEnvironment.production,
      ],
      limitations: const [
        'no-cicd-enforcement',
        'no-cryptographic-signature-verification',
        'no-automatic-waiver-consumption',
      ],
    );
  }

  static List<ReleaseGovernanceRule> _rules() {
    return [
      _rule(
        ruleId: 'RG001',
        ruleSetId: 'release-integrity',
        name: 'Project consistency',
        target: ReleaseGovernanceRuleTarget.projectConsistency,
        operator: ReleaseGovernanceRuleOperator.isTrue,
        severity: ReleaseGovernanceRuleSeverity.critical,
        waiver: ReleaseGovernanceWaiverCapability.forbidden,
        order: 1,
      ),
      _rule(
        ruleId: 'RG002',
        ruleSetId: 'release-integrity',
        name: 'Commit consistency',
        target: ReleaseGovernanceRuleTarget.commitConsistency,
        operator: ReleaseGovernanceRuleOperator.isTrue,
        severity: ReleaseGovernanceRuleSeverity.critical,
        waiver: ReleaseGovernanceWaiverCapability.forbidden,
        order: 2,
      ),
      _rule(
        ruleId: 'RG003',
        ruleSetId: 'technical-gate',
        name: 'Quality Gate available',
        target: ReleaseGovernanceRuleTarget.qualityGateDecision,
        operator: ReleaseGovernanceRuleOperator.isAvailable,
        severity: ReleaseGovernanceRuleSeverity.blocking,
        waiver: ReleaseGovernanceWaiverCapability.forbidden,
        order: 3,
      ),
      _rule(
        ruleId: 'RG004',
        ruleSetId: 'technical-gate',
        name: 'Quality Gate decision permitted',
        target: ReleaseGovernanceRuleTarget.qualityGateDecision,
        operator: ReleaseGovernanceRuleOperator.inSet,
        expected: const ReleaseGovernanceSetValue(['passed', 'partial']),
        severity: ReleaseGovernanceRuleSeverity.critical,
        waiver: ReleaseGovernanceWaiverCapability.forbidden,
        order: 4,
      ),
      _rule(
        ruleId: 'RG005',
        ruleSetId: 'technical-gate',
        name: 'Quality Gate compatible',
        target: ReleaseGovernanceRuleTarget.qualityGateCompatibility,
        operator: ReleaseGovernanceRuleOperator.isCompatible,
        severity: ReleaseGovernanceRuleSeverity.critical,
        waiver: ReleaseGovernanceWaiverCapability.forbidden,
        order: 5,
      ),
      _rule(
        ruleId: 'RG006',
        ruleSetId: 'technical-gate',
        name: 'Quality Gate eligible',
        target: ReleaseGovernanceRuleTarget.qualityGateEligibility,
        operator: ReleaseGovernanceRuleOperator.isValid,
        severity: ReleaseGovernanceRuleSeverity.blocking,
        waiver: ReleaseGovernanceWaiverCapability.allowedWithConditions,
        order: 6,
      ),
      _rule(
        ruleId: 'RG007',
        ruleSetId: 'technical-gate',
        name: 'Quality Gate minimum coverage',
        target: ReleaseGovernanceRuleTarget.qualityGateCoverage,
        operator: ReleaseGovernanceRuleOperator.greaterThanOrEqual,
        expected: const ReleaseGovernancePercentageValue(80),
        severity: ReleaseGovernanceRuleSeverity.blocking,
        waiver: ReleaseGovernanceWaiverCapability.allowedWithConditions,
        order: 7,
      ),
      _rule(
        ruleId: 'RG008',
        ruleSetId: 'technical-gate',
        name: 'Quality Gate freshness',
        target: ReleaseGovernanceRuleTarget.qualityGateAge,
        operator: ReleaseGovernanceRuleOperator.lessThanOrEqual,
        expected: const ReleaseGovernanceDurationValue('P7D'),
        severity: ReleaseGovernanceRuleSeverity.blocking,
        waiver: ReleaseGovernanceWaiverCapability.allowedWithConditions,
        order: 8,
      ),
      _rule(
        ruleId: 'RG009',
        ruleSetId: 'environment-governance',
        name: 'Release environment supported',
        target: ReleaseGovernanceRuleTarget.releaseEnvironment,
        operator: ReleaseGovernanceRuleOperator.inSet,
        expected: const ReleaseGovernanceSetValue([
          'development',
          'test',
          'qa',
          'staging',
          'preProduction',
          'production',
        ]),
        severity: ReleaseGovernanceRuleSeverity.blocking,
        waiver: ReleaseGovernanceWaiverCapability.forbidden,
        order: 9,
      ),
      _rule(
        ruleId: 'RG010',
        ruleSetId: 'environment-governance',
        name: 'Release type supported',
        target: ReleaseGovernanceRuleTarget.releaseType,
        operator: ReleaseGovernanceRuleOperator.inSet,
        expected: const ReleaseGovernanceSetValue([
          'development',
          'internal',
          'beta',
          'releaseCandidate',
          'production',
          'hotfix',
          'rollback',
          'emergency',
        ]),
        severity: ReleaseGovernanceRuleSeverity.blocking,
        waiver: ReleaseGovernanceWaiverCapability.forbidden,
        order: 10,
      ),
      _rule(
        ruleId: 'RG011',
        ruleSetId: 'approval-governance',
        name: 'Required approvals complete',
        target: ReleaseGovernanceRuleTarget.missingApprovalCount,
        operator: ReleaseGovernanceRuleOperator.equals,
        expected: const ReleaseGovernanceIntegerValue(0),
        severity: ReleaseGovernanceRuleSeverity.blocking,
        waiver: ReleaseGovernanceWaiverCapability.forbidden,
        order: 11,
      ),
      _rule(
        ruleId: 'RG012',
        ruleSetId: 'approval-governance',
        name: 'No rejected approvals',
        target: ReleaseGovernanceRuleTarget.rejectedApprovalCount,
        operator: ReleaseGovernanceRuleOperator.equals,
        expected: const ReleaseGovernanceIntegerValue(0),
        severity: ReleaseGovernanceRuleSeverity.critical,
        waiver: ReleaseGovernanceWaiverCapability.forbidden,
        order: 12,
      ),
      _rule(
        ruleId: 'RG013',
        ruleSetId: 'approval-governance',
        name: 'Separation of duties satisfied',
        target: ReleaseGovernanceRuleTarget.separationOfDutiesSatisfied,
        operator: ReleaseGovernanceRuleOperator.isTrue,
        severity: ReleaseGovernanceRuleSeverity.blocking,
        waiver: ReleaseGovernanceWaiverCapability.forbidden,
        order: 13,
      ),
      _rule(
        ruleId: 'RG014',
        ruleSetId: 'approval-governance',
        name: 'No expired approvals',
        target: ReleaseGovernanceRuleTarget.expiredApprovalCount,
        operator: ReleaseGovernanceRuleOperator.equals,
        expected: const ReleaseGovernanceIntegerValue(0),
        severity: ReleaseGovernanceRuleSeverity.blocking,
        waiver: ReleaseGovernanceWaiverCapability.allowedWithConditions,
        order: 14,
      ),
      _rule(
        ruleId: 'RG015',
        ruleSetId: 'waiver-governance',
        name: 'No invalid waivers',
        target: ReleaseGovernanceRuleTarget.invalidWaiverCount,
        operator: ReleaseGovernanceRuleOperator.equals,
        expected: const ReleaseGovernanceIntegerValue(0),
        severity: ReleaseGovernanceRuleSeverity.critical,
        waiver: ReleaseGovernanceWaiverCapability.forbidden,
        order: 15,
      ),
      _rule(
        ruleId: 'RG016',
        ruleSetId: 'waiver-governance',
        name: 'No expired waivers',
        target: ReleaseGovernanceRuleTarget.expiredWaiverCount,
        operator: ReleaseGovernanceRuleOperator.equals,
        expected: const ReleaseGovernanceIntegerValue(0),
        severity: ReleaseGovernanceRuleSeverity.blocking,
        waiver: ReleaseGovernanceWaiverCapability.forbidden,
        order: 16,
      ),
      _rule(
        ruleId: 'RG017',
        ruleSetId: 'waiver-governance',
        name: 'Waiver limit satisfied',
        target: ReleaseGovernanceRuleTarget.waiverLimitSatisfied,
        operator: ReleaseGovernanceRuleOperator.isTrue,
        severity: ReleaseGovernanceRuleSeverity.blocking,
        waiver: ReleaseGovernanceWaiverCapability.forbidden,
        order: 17,
      ),
      _rule(
        ruleId: 'RG018',
        ruleSetId: 'evidence-integrity',
        name: 'Approval evidence complete',
        target: ReleaseGovernanceRuleTarget.approvalEvidenceComplete,
        operator: ReleaseGovernanceRuleOperator.isTrue,
        severity: ReleaseGovernanceRuleSeverity.blocking,
        waiver: ReleaseGovernanceWaiverCapability.allowedWithConditions,
        order: 18,
      ),
      _rule(
        ruleId: 'RG019',
        ruleSetId: 'evidence-integrity',
        name: 'Waiver evidence complete',
        target: ReleaseGovernanceRuleTarget.waiverEvidenceComplete,
        operator: ReleaseGovernanceRuleOperator.isTrue,
        severity: ReleaseGovernanceRuleSeverity.blocking,
        requirement: ReleaseGovernanceRuleRequirement.optional,
        waiver: ReleaseGovernanceWaiverCapability.allowed,
        order: 19,
      ),
      _rule(
        ruleId: 'RG020',
        ruleSetId: 'final-authorization',
        name: 'Release artifacts present',
        target: ReleaseGovernanceRuleTarget.releaseArtifactCount,
        operator: ReleaseGovernanceRuleOperator.greaterThan,
        expected: const ReleaseGovernanceIntegerValue(0),
        severity: ReleaseGovernanceRuleSeverity.warning,
        requirement: ReleaseGovernanceRuleRequirement.optional,
        waiver: ReleaseGovernanceWaiverCapability.allowed,
        order: 20,
      ),
    ];
  }

  static ReleaseGovernanceRule _rule({
    required String ruleId,
    required String ruleSetId,
    required String name,
    required ReleaseGovernanceRuleTarget target,
    required ReleaseGovernanceRuleOperator operator,
    ReleaseGovernanceRuleValue? expected,
    ReleaseGovernanceRuleSeverity severity =
        ReleaseGovernanceRuleSeverity.blocking,
    ReleaseGovernanceRuleRequirement requirement =
        ReleaseGovernanceRuleRequirement.required,
    ReleaseGovernanceWaiverCapability waiver =
        ReleaseGovernanceWaiverCapability.forbidden,
    required int order,
  }) {
    return ReleaseGovernanceRule(
      ruleId: ruleId,
      ruleSetId: ruleSetId,
      name: name,
      description: name,
      target: target,
      operator: operator,
      expectedValue: expected,
      severity: severity,
      requirement: requirement,
      missingDataPolicy: ReleaseGovernanceMissingDataPolicy.reject,
      incompatibleDataPolicy: ReleaseGovernanceIncompatibleDataPolicy.reject,
      evidenceRequirement: kReleaseGovernanceEvidenceRequirement,
      waiverCapability: waiver,
      rationale: name,
      order: order,
    );
  }

  static List<ReleaseGovernanceRuleSet> _ruleSets() {
    return [
      _ruleSet(
        ruleSetId: 'release-integrity',
        name: 'Release Integrity',
        order: 1,
        ruleIds: ['RG001', 'RG002'],
      ),
      _ruleSet(
        ruleSetId: 'technical-gate',
        name: 'Technical Gate',
        order: 2,
        ruleIds: ['RG003', 'RG004', 'RG005', 'RG006', 'RG007', 'RG008'],
      ),
      _ruleSet(
        ruleSetId: 'approval-governance',
        name: 'Approval Governance',
        order: 3,
        ruleIds: ['RG011', 'RG012', 'RG013', 'RG014'],
      ),
      _ruleSet(
        ruleSetId: 'waiver-governance',
        name: 'Waiver Governance',
        order: 4,
        ruleIds: ['RG015', 'RG016', 'RG017'],
      ),
      _ruleSet(
        ruleSetId: 'environment-governance',
        name: 'Environment Governance',
        order: 5,
        ruleIds: ['RG009', 'RG010'],
      ),
      _ruleSet(
        ruleSetId: 'evidence-integrity',
        name: 'Evidence Integrity',
        order: 6,
        ruleIds: ['RG018', 'RG019'],
      ),
      _ruleSet(
        ruleSetId: 'final-authorization',
        name: 'Final Authorization',
        order: 7,
        ruleIds: ['RG020'],
        required: false,
        severity: ReleaseGovernanceRuleSeverity.warning,
      ),
    ];
  }

  static ReleaseGovernanceRuleSet _ruleSet({
    required String ruleSetId,
    required String name,
    required int order,
    required List<String> ruleIds,
    bool required = true,
    ReleaseGovernanceRuleSeverity severity =
        ReleaseGovernanceRuleSeverity.blocking,
  }) {
    return ReleaseGovernanceRuleSet(
      ruleSetId: ruleSetId,
      name: name,
      description: name,
      order: order,
      enabled: true,
      required: required,
      severity: severity,
      aggregationMode: ReleaseGovernanceRuleSetAggregationMode.all,
      ruleIds: ruleIds,
      rationale: name,
    );
  }

  static List<ReleaseApprovalRequirement> _approvalRequirements() {
    const sod = ReleaseSeparationOfDutiesRule(
      ruleId: 'sod-production-v1',
      prohibitedSameApproverTypes: [
        ReleaseApprovalType.engineering,
        ReleaseApprovalType.quality,
        ReleaseApprovalType.releaseManager,
      ],
      prohibitedAuthorityGroups: ['engineering', 'quality'],
      minimumDistinctApprovers: 2,
      requesterCannotApprove: true,
      waiverIssuerCannotApprove: true,
      emergencyOverrides: true,
      rationale: 'Production releases require distinct approvers',
    );

    return [
      ReleaseApprovalRequirement(
        requirementId: 'dev-optional',
        approvalType: ReleaseApprovalType.engineering,
        minimumCount: 0,
        distinctApproversRequired: false,
        environmentScope: [ReleaseEnvironment.development],
        releaseTypeScope: [ReleaseType.development],
        requiredForDecisions: [ReleaseGovernanceDecision.approved],
        evidenceRequired: false,
        order: 1,
        enabled: true,
        allowedAuthorityIds: ['eng-dev'],
      ),
      ReleaseApprovalRequirement(
        requirementId: 'qa-engineering',
        approvalType: ReleaseApprovalType.engineering,
        minimumCount: 1,
        distinctApproversRequired: true,
        environmentScope: [ReleaseEnvironment.qa, ReleaseEnvironment.staging],
        releaseTypeScope: [
          ReleaseType.beta,
          ReleaseType.releaseCandidate,
        ],
        requiredForDecisions: [
          ReleaseGovernanceDecision.approved,
          ReleaseGovernanceDecision.approvedWithConditions,
        ],
        evidenceRequired: true,
        order: 2,
        enabled: true,
        allowedAuthorityIds: ['eng-qa'],
      ),
      ReleaseApprovalRequirement(
        requirementId: 'qa-quality',
        approvalType: ReleaseApprovalType.quality,
        minimumCount: 1,
        distinctApproversRequired: true,
        environmentScope: [ReleaseEnvironment.qa, ReleaseEnvironment.staging],
        releaseTypeScope: [
          ReleaseType.beta,
          ReleaseType.releaseCandidate,
        ],
        requiredForDecisions: [
          ReleaseGovernanceDecision.approved,
          ReleaseGovernanceDecision.approvedWithConditions,
        ],
        evidenceRequired: true,
        order: 3,
        enabled: true,
        allowedAuthorityIds: ['quality-qa'],
      ),
      ReleaseApprovalRequirement(
        requirementId: 'prod-engineering',
        approvalType: ReleaseApprovalType.engineering,
        minimumCount: 1,
        distinctApproversRequired: true,
        environmentScope: [ReleaseEnvironment.production],
        releaseTypeScope: [ReleaseType.production],
        requiredForDecisions: [
          ReleaseGovernanceDecision.approved,
          ReleaseGovernanceDecision.approvedWithConditions,
        ],
        evidenceRequired: true,
        separationOfDutiesRule: sod,
        order: 4,
        enabled: true,
        allowedAuthorityIds: ['eng-prod'],
      ),
      ReleaseApprovalRequirement(
        requirementId: 'prod-quality',
        approvalType: ReleaseApprovalType.quality,
        minimumCount: 1,
        distinctApproversRequired: true,
        environmentScope: [ReleaseEnvironment.production],
        releaseTypeScope: [ReleaseType.production],
        requiredForDecisions: [
          ReleaseGovernanceDecision.approved,
          ReleaseGovernanceDecision.approvedWithConditions,
        ],
        evidenceRequired: true,
        separationOfDutiesRule: sod,
        order: 5,
        enabled: true,
        allowedAuthorityIds: ['quality-prod'],
      ),
      ReleaseApprovalRequirement(
        requirementId: 'prod-release-manager',
        approvalType: ReleaseApprovalType.releaseManager,
        minimumCount: 1,
        distinctApproversRequired: true,
        environmentScope: [ReleaseEnvironment.production],
        releaseTypeScope: [ReleaseType.production, ReleaseType.hotfix],
        requiredForDecisions: [
          ReleaseGovernanceDecision.approved,
          ReleaseGovernanceDecision.approvedWithConditions,
        ],
        evidenceRequired: true,
        separationOfDutiesRule: sod,
        order: 6,
        enabled: true,
        allowedAuthorityIds: ['rm-prod'],
      ),
      ReleaseApprovalRequirement(
        requirementId: 'hotfix-emergency',
        approvalType: ReleaseApprovalType.emergency,
        minimumCount: 1,
        distinctApproversRequired: true,
        environmentScope: [ReleaseEnvironment.production],
        releaseTypeScope: [ReleaseType.hotfix, ReleaseType.emergency],
        requiredForDecisions: [
          ReleaseGovernanceDecision.approvedWithConditions,
        ],
        evidenceRequired: true,
        order: 7,
        enabled: true,
        allowedAuthorityIds: ['emergency-prod'],
      ),
      ReleaseApprovalRequirement(
        requirementId: 'rollback-operations',
        approvalType: ReleaseApprovalType.operations,
        minimumCount: 1,
        distinctApproversRequired: true,
        environmentScope: [
          ReleaseEnvironment.production,
          ReleaseEnvironment.staging,
        ],
        releaseTypeScope: [ReleaseType.rollback],
        requiredForDecisions: [
          ReleaseGovernanceDecision.approved,
          ReleaseGovernanceDecision.approvedWithConditions,
        ],
        evidenceRequired: true,
        order: 8,
        enabled: true,
        allowedAuthorityIds: ['ops-rollback'],
      ),
    ];
  }

  static ReleaseWaiverPolicy _waiverPolicy() {
    return const ReleaseWaiverPolicy(
      maximumActiveWaivers: 3,
      maximumDuration: 'P7D',
      allowedEnvironments: [
        ReleaseEnvironment.development,
        ReleaseEnvironment.qa,
        ReleaseEnvironment.staging,
        ReleaseEnvironment.production,
      ],
      allowedSeverities: [
        ReleaseGovernanceRuleSeverity.warning,
        ReleaseGovernanceRuleSeverity.blocking,
      ],
      allowedAuthorities: [
        'waiver-dev',
        'waiver-qa',
        'waiver-prod-rm',
      ],
      compensatingControlsRequired: true,
      evidenceRequired: true,
      singleUseForProduction: true,
      expirationRequired: true,
      commitBindingForProduction: true,
      releaseBindingRequired: true,
      criticalForbidden: true,
      projectConsistencyForbidden: true,
      commitConsistencyForbidden: true,
      incompatibleSourcesForbidden: true,
    );
  }
}
