// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPRazC3wOs-x7IdatMy26Dr81pEi4Xz44',
    appId: '1:950139833317:web:4f94d4108daf8ab31ebd0c',
    messagingSenderId: '950139833317',
    projectId: 'masterpalm-58c46',
    authDomain: 'masterpalm-58c46.firebaseapp.com',
    storageBucket: 'masterpalm-58c46.firebasestorage.app',
    measurementId: 'G-0F0ZRT1S6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1el5pCGqdP8RrWHZsHl5hUFcFqyp4B5U',
    appId: '1:950139833317:android:01d76e9d022ae1851ebd0c',
    messagingSenderId: '950139833317',
    projectId: 'masterpalm-58c46',
    storageBucket: 'masterpalm-58c46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvqP8AawC81TALQ2kc9VCB9KYXsfVGmHo',
    appId: '1:950139833317:ios:579dd14e5cc61a5b1ebd0c',
    messagingSenderId: '950139833317',
    projectId: 'masterpalm-58c46',
    storageBucket: 'masterpalm-58c46.firebasestorage.app',
    iosBundleId: 'com.example.tempNaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvqP8AawC81TALQ2kc9VCB9KYXsfVGmHo',
    appId: '1:950139833317:ios:579dd14e5cc61a5b1ebd0c',
    messagingSenderId: '950139833317',
    projectId: 'masterpalm-58c46',
    storageBucket: 'masterpalm-58c46.firebasestorage.app',
    iosBundleId: 'com.example.tempNaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPRazC3wOs-x7IdatMy26Dr81pEi4Xz44',
    appId: '1:950139833317:web:4f94d4108daf8ab31ebd0c',
    messagingSenderId: '950139833317',
    projectId: 'masterpalm-58c46',
    authDomain: 'masterpalm-58c46.firebaseapp.com',
    storageBucket: 'masterpalm-58c46.firebasestorage.app',
    measurementId: 'G-0F0ZRT1S6G',
  );
}
