import '../../models/release_evidence/release_evidence_collection_rule.dart';
import '../../models/release_evidence/release_evidence_enums.dart';
import '../../models/release_evidence/release_evidence_policy.dart';
import '../../models/release_evidence/release_evidence_rule_value.dart';
import '../../models/release_governance/release_governance_enums.dart';

/// Candidate release evidence collection policy v1.
class ReleaseEvidencePolicyV1 {
  const ReleaseEvidencePolicyV1._();

  static const policyId = 'release-evidence-v1';

  static ReleaseEvidencePolicy create() {
    final rules = _rules();
    return ReleaseEvidencePolicy(
      metadata: const ReleaseEvidencePolicyMetadata(
        policyId: policyId,
        policyVersion: 1,
        displayName: 'MasterPalm Release Evidence',
        description:
            'Candidate release evidence collection policy organizing published platform artifacts into auditable bundles.',
        owner: 'MasterPalm Engineering Governance',
        status: ReleaseEvidencePolicyStatus.candidate,
        schemaVersion: ReleaseEvidencePolicy.currentSchemaVersion,
        calculationVersion: ReleaseEvidencePolicy.currentCalculationVersion,
        canonicalizationVersion:
            ReleaseEvidencePolicy.currentCanonicalizationVersion,
        createdAt: '2026-01-01T00:00:00.000Z',
        rationale:
            'Conservative candidate policy for release evidence bundles without recalculating origin engines.',
        changelog: [
          ReleaseEvidencePolicyChangelogEntry(
            version: 1,
            summary: 'Initial candidate release evidence policy',
            author: 'MasterPalm Engineering Governance',
            createdAt: '2026-01-01T00:00:00.000Z',
          ),
        ],
        tags: ['release-evidence', 'candidate'],
      ),
      governance: const ReleaseEvidencePolicyGovernance(
        policyOwner: 'MasterPalm Engineering Governance',
        approvalAuthority: 'MasterPalm Engineering Governance',
        policyApprovalStatus: 'candidate',
        versioningStrategy: 'immutable-version-on-normative-change',
        rollbackPolicy: 'explicit-version-selection-only',
        evidenceRequirements:
            'quality-gate-release-decision-references-with-fingerprints',
        compatibilityRequirements:
            'explicit-compatibility-check-before-collection',
        retentionRequirements: 'policy-id-version-fingerprints-preserved',
        reviewCadence: 'quarterly',
        escalationAuthority: 'MasterPalm Engineering Governance',
        attestationAuthority: 'MasterPalm Engineering Governance',
        verificationAuthority: 'MasterPalm Engineering Governance',
      ),
      rules: rules,
      ruleSets: _ruleSets(),
      requiredEvidenceTypes: const [
        ReleaseEvidenceType.qualityGate,
        ReleaseEvidenceType.releaseGovernance,
      ],
      requiredArtifactTypes: const [
        ReleaseEvidenceArtifactType.qualityGate,
        ReleaseEvidenceArtifactType.releaseGovernance,
      ],
      compatibilityPolicy: const ReleaseEvidenceCompatibilityPolicy(
        supportedSchemas: [1],
        allowedQualityGatePolicyIds: ['quality-gate-release-v1'],
        allowedQualityGatePolicyVersions: [1],
        allowedReleaseGovernancePolicyIds: ['release-governance-v1'],
        allowedReleaseGovernancePolicyVersions: [1],
        allowedAttestationPolicyIds: ['release-attestation-v1'],
        allowedVerificationPolicyIds: ['release-verification-v1'],
      ),
      eligibilityPolicy: const ReleaseEvidenceEligibilityPolicy(
        requireReleaseContext: true,
        requireQualityGate: true,
        requireReleaseDecision: true,
        requireNormativeEvidence: true,
        allowCandidatePolicy: true,
        supportedEnvironments: [
          ReleaseEnvironment.development,
          ReleaseEnvironment.test,
          ReleaseEnvironment.qa,
          ReleaseEnvironment.staging,
          ReleaseEnvironment.preProduction,
          ReleaseEnvironment.production,
        ],
        supportedReleaseTypes: [
          ReleaseType.development,
          ReleaseType.internal,
          ReleaseType.beta,
          ReleaseType.releaseCandidate,
          ReleaseType.production,
          ReleaseType.hotfix,
        ],
      ),
      coveragePolicy: const ReleaseEvidenceCoveragePolicy(
        minimumEvidenceCoverage: 100,
        minimumAttestationCoverage: 100,
        minimumProvenanceCoverage: 100,
        minimumSourceCoverage: 100,
        minimumNormativeEvidenceCount: 2,
        minimumValidAttestationCount: 1,
      ),
      retentionPolicy: const ReleaseEvidenceRetentionPolicy(),
      attestationRequirements: const [
        ReleaseEvidenceAttestationRequirementRef(
          requirementId: 'bundle-integrity',
          attestationType: ReleaseAttestationType.evidenceBundleIntegrity,
          required: true,
        ),
      ],
      limitations: const [
        'no-cryptographic-verification',
        'no-remote-evidence-fetch',
        'no-cicd-integration',
      ],
    );
  }

  static List<ReleaseEvidenceCollectionRule> _rules() {
    return [
      _rule(
        ruleId: 'RE001',
        ruleSetId: 'subject-integrity',
        name: 'Project consistency',
        target: ReleaseEvidenceCollectionRuleTarget.projectConsistency,
        operator: ReleaseEvidenceCollectionRuleOperator.isTrue,
        expected: const ReleaseEvidenceBooleanValue(true),
        severity: ReleaseEvidenceCollectionRuleSeverity.critical,
        order: 1,
      ),
      _rule(
        ruleId: 'RE002',
        ruleSetId: 'subject-integrity',
        name: 'Commit consistency',
        target: ReleaseEvidenceCollectionRuleTarget.commitConsistency,
        operator: ReleaseEvidenceCollectionRuleOperator.isTrue,
        expected: const ReleaseEvidenceBooleanValue(true),
        severity: ReleaseEvidenceCollectionRuleSeverity.critical,
        order: 2,
      ),
      _rule(
        ruleId: 'RE003',
        ruleSetId: 'technical-evidence',
        name: 'Quality Gate reference present',
        target: ReleaseEvidenceCollectionRuleTarget.qualityGatePresent,
        operator: ReleaseEvidenceCollectionRuleOperator.isTrue,
        expected: const ReleaseEvidenceBooleanValue(true),
        severity: ReleaseEvidenceCollectionRuleSeverity.blocking,
        order: 3,
      ),
      _rule(
        ruleId: 'RE004',
        ruleSetId: 'governance-evidence',
        name: 'Release Decision reference present',
        target: ReleaseEvidenceCollectionRuleTarget.releaseDecisionPresent,
        operator: ReleaseEvidenceCollectionRuleOperator.isTrue,
        expected: const ReleaseEvidenceBooleanValue(true),
        severity: ReleaseEvidenceCollectionRuleSeverity.critical,
        order: 4,
      ),
      _rule(
        ruleId: 'RE005',
        ruleSetId: 'technical-evidence',
        name: 'Quality Gate fingerprint present',
        target: ReleaseEvidenceCollectionRuleTarget.fingerprintPresent,
        selector: const ReleaseEvidenceCollectionRuleSelector(
          evidenceType: ReleaseEvidenceType.qualityGate,
        ),
        operator: ReleaseEvidenceCollectionRuleOperator.isTrue,
        expected: const ReleaseEvidenceBooleanValue(true),
        severity: ReleaseEvidenceCollectionRuleSeverity.blocking,
        order: 5,
      ),
      _rule(
        ruleId: 'RE006',
        ruleSetId: 'governance-evidence',
        name: 'Release Decision fingerprint present',
        target: ReleaseEvidenceCollectionRuleTarget.fingerprintPresent,
        selector: const ReleaseEvidenceCollectionRuleSelector(
          evidenceType: ReleaseEvidenceType.releaseGovernance,
        ),
        operator: ReleaseEvidenceCollectionRuleOperator.isTrue,
        expected: const ReleaseEvidenceBooleanValue(true),
        severity: ReleaseEvidenceCollectionRuleSeverity.critical,
        order: 6,
      ),
      _rule(
        ruleId: 'RE007',
        ruleSetId: 'source-consistency',
        name: 'Source compatibility',
        target: ReleaseEvidenceCollectionRuleTarget.sourceCompatible,
        operator: ReleaseEvidenceCollectionRuleOperator.isTrue,
        expected: const ReleaseEvidenceBooleanValue(true),
        severity: ReleaseEvidenceCollectionRuleSeverity.blocking,
        order: 7,
      ),
      _rule(
        ruleId: 'RE008',
        ruleSetId: 'source-consistency',
        name: 'Source availability',
        target: ReleaseEvidenceCollectionRuleTarget.sourceAvailable,
        operator: ReleaseEvidenceCollectionRuleOperator.isTrue,
        expected: const ReleaseEvidenceBooleanValue(true),
        severity: ReleaseEvidenceCollectionRuleSeverity.blocking,
        order: 8,
      ),
      _rule(
        ruleId: 'RE009',
        ruleSetId: 'technical-evidence',
        name: 'Minimum evidence count',
        target: ReleaseEvidenceCollectionRuleTarget.evidenceCount,
        operator: ReleaseEvidenceCollectionRuleOperator.greaterThanOrEqual,
        expected: const ReleaseEvidenceIntegerValue(2),
        severity: ReleaseEvidenceCollectionRuleSeverity.blocking,
        order: 9,
      ),
      _rule(
        ruleId: 'RE010',
        ruleSetId: 'technical-evidence',
        name: 'Normative evidence present',
        target: ReleaseEvidenceCollectionRuleTarget.normativeEvidenceCount,
        operator: ReleaseEvidenceCollectionRuleOperator.greaterThan,
        expected: const ReleaseEvidenceIntegerValue(0),
        severity: ReleaseEvidenceCollectionRuleSeverity.blocking,
        order: 10,
      ),
      _rule(
        ruleId: 'RE011',
        ruleSetId: 'provenance-integrity',
        name: 'Provenance present',
        target: ReleaseEvidenceCollectionRuleTarget.provenancePresent,
        operator: ReleaseEvidenceCollectionRuleOperator.isTrue,
        expected: const ReleaseEvidenceBooleanValue(true),
        severity: ReleaseEvidenceCollectionRuleSeverity.blocking,
        order: 11,
      ),
      _rule(
        ruleId: 'RE012',
        ruleSetId: 'provenance-integrity',
        name: 'Provenance complete',
        target: ReleaseEvidenceCollectionRuleTarget.provenanceComplete,
        operator: ReleaseEvidenceCollectionRuleOperator.isTrue,
        expected: const ReleaseEvidenceBooleanValue(true),
        severity: ReleaseEvidenceCollectionRuleSeverity.blocking,
        order: 12,
      ),
      _rule(
        ruleId: 'RE013',
        ruleSetId: 'attestation-integrity',
        name: 'Required attestations present',
        target: ReleaseEvidenceCollectionRuleTarget.requiredAttestationCount,
        operator: ReleaseEvidenceCollectionRuleOperator.equals,
        expected: const ReleaseEvidenceIntegerValue(1),
        severity: ReleaseEvidenceCollectionRuleSeverity.blocking,
        order: 13,
      ),
      _rule(
        ruleId: 'RE014',
        ruleSetId: 'attestation-integrity',
        name: 'No invalid attestations',
        target: ReleaseEvidenceCollectionRuleTarget.invalidAttestationCount,
        operator: ReleaseEvidenceCollectionRuleOperator.equals,
        expected: const ReleaseEvidenceIntegerValue(0),
        severity: ReleaseEvidenceCollectionRuleSeverity.critical,
        order: 14,
      ),
      _rule(
        ruleId: 'RE015',
        ruleSetId: 'attestation-integrity',
        name: 'No expired attestations',
        target: ReleaseEvidenceCollectionRuleTarget.expiredAttestationCount,
        operator: ReleaseEvidenceCollectionRuleOperator.equals,
        expected: const ReleaseEvidenceIntegerValue(0),
        severity: ReleaseEvidenceCollectionRuleSeverity.critical,
        order: 15,
      ),
      _rule(
        ruleId: 'RE016',
        ruleSetId: 'attestation-integrity',
        name: 'Unverified attestations within policy',
        target: ReleaseEvidenceCollectionRuleTarget.unverifiedAttestationCount,
        operator: ReleaseEvidenceCollectionRuleOperator.lessThanOrEqual,
        expected: const ReleaseEvidenceIntegerValue(2),
        severity: ReleaseEvidenceCollectionRuleSeverity.warning,
        requirement: ReleaseEvidenceCollectionRuleRequirement.optional,
        order: 16,
      ),
      _rule(
        ruleId: 'RE017',
        ruleSetId: 'governance-evidence',
        name: 'Release authorization consistency',
        target:
            ReleaseEvidenceCollectionRuleTarget.releaseAuthorizationConsistent,
        operator: ReleaseEvidenceCollectionRuleOperator.isTrue,
        expected: const ReleaseEvidenceBooleanValue(true),
        severity: ReleaseEvidenceCollectionRuleSeverity.critical,
        order: 17,
      ),
      _rule(
        ruleId: 'RE018',
        ruleSetId: 'source-consistency',
        name: 'Source set complete',
        target: ReleaseEvidenceCollectionRuleTarget.sourceSetComplete,
        operator: ReleaseEvidenceCollectionRuleOperator.isTrue,
        expected: const ReleaseEvidenceBooleanValue(true),
        severity: ReleaseEvidenceCollectionRuleSeverity.blocking,
        order: 18,
      ),
      _rule(
        ruleId: 'RE019',
        ruleSetId: 'technical-evidence',
        name: 'Evidence freshness',
        target: ReleaseEvidenceCollectionRuleTarget.evidenceFreshness,
        operator: ReleaseEvidenceCollectionRuleOperator.lessThanOrEqual,
        expected: const ReleaseEvidenceDurationValue('P7D'),
        severity: ReleaseEvidenceCollectionRuleSeverity.warning,
        requirement: ReleaseEvidenceCollectionRuleRequirement.optional,
        order: 19,
      ),
      _rule(
        ruleId: 'RE020',
        ruleSetId: 'attestation-integrity',
        name: 'Attestation coverage minimum',
        target: ReleaseEvidenceCollectionRuleTarget.validAttestationCount,
        operator: ReleaseEvidenceCollectionRuleOperator.greaterThanOrEqual,
        expected: const ReleaseEvidenceIntegerValue(1),
        severity: ReleaseEvidenceCollectionRuleSeverity.blocking,
        order: 20,
      ),
      _rule(
        ruleId: 'RE021',
        ruleSetId: 'provenance-integrity',
        name: 'Provenance coverage minimum',
        target: ReleaseEvidenceCollectionRuleTarget.provenancePresent,
        operator: ReleaseEvidenceCollectionRuleOperator.isTrue,
        expected: const ReleaseEvidenceBooleanValue(true),
        severity: ReleaseEvidenceCollectionRuleSeverity.blocking,
        order: 21,
      ),
      _rule(
        ruleId: 'RE022',
        ruleSetId: 'verification-readiness',
        name: 'Schema compatibility',
        target: ReleaseEvidenceCollectionRuleTarget.policyConsistency,
        operator: ReleaseEvidenceCollectionRuleOperator.isTrue,
        expected: const ReleaseEvidenceBooleanValue(true),
        severity: ReleaseEvidenceCollectionRuleSeverity.critical,
        order: 22,
      ),
    ];
  }

  static List<ReleaseEvidenceCollectionRuleSet> _ruleSets() {
    return const [
      ReleaseEvidenceCollectionRuleSet(
        ruleSetId: 'subject-integrity',
        name: 'Subject integrity',
        description: 'Project and commit consistency across bundle sources.',
        order: 1,
        enabled: true,
        required: true,
        severity: ReleaseEvidenceCollectionRuleSeverity.critical,
        aggregationMode: ReleaseEvidenceRuleSetAggregationMode.all,
        ruleIds: ['RE001', 'RE002'],
        rationale: 'Subject integrity is mandatory for auditable bundles.',
      ),
      ReleaseEvidenceCollectionRuleSet(
        ruleSetId: 'technical-evidence',
        name: 'Technical evidence',
        description: 'Quality Gate and normative technical evidence.',
        order: 2,
        enabled: true,
        required: true,
        severity: ReleaseEvidenceCollectionRuleSeverity.blocking,
        aggregationMode: ReleaseEvidenceRuleSetAggregationMode.all,
        ruleIds: ['RE003', 'RE005', 'RE009', 'RE010', 'RE019'],
        rationale: 'Technical evidence must be present and fresh.',
      ),
      ReleaseEvidenceCollectionRuleSet(
        ruleSetId: 'governance-evidence',
        name: 'Governance evidence',
        description: 'Release governance decision references and consistency.',
        order: 3,
        enabled: true,
        required: true,
        severity: ReleaseEvidenceCollectionRuleSeverity.critical,
        aggregationMode: ReleaseEvidenceRuleSetAggregationMode.all,
        ruleIds: ['RE004', 'RE006', 'RE017'],
        rationale: 'Governance evidence anchors release authorization.',
      ),
      ReleaseEvidenceCollectionRuleSet(
        ruleSetId: 'provenance-integrity',
        name: 'Provenance integrity',
        description: 'Provenance presence and completeness.',
        order: 4,
        enabled: true,
        required: true,
        severity: ReleaseEvidenceCollectionRuleSeverity.blocking,
        aggregationMode: ReleaseEvidenceRuleSetAggregationMode.all,
        ruleIds: ['RE011', 'RE012', 'RE021'],
        rationale: 'Provenance must be present for production readiness.',
      ),
      ReleaseEvidenceCollectionRuleSet(
        ruleSetId: 'attestation-integrity',
        name: 'Attestation integrity',
        description: 'Attestation counts and validity.',
        order: 5,
        enabled: true,
        required: true,
        severity: ReleaseEvidenceCollectionRuleSeverity.blocking,
        aggregationMode: ReleaseEvidenceRuleSetAggregationMode.all,
        ruleIds: ['RE013', 'RE014', 'RE015', 'RE016', 'RE020'],
        rationale: 'Attestations must be valid and sufficient.',
      ),
      ReleaseEvidenceCollectionRuleSet(
        ruleSetId: 'source-consistency',
        name: 'Source consistency',
        description: 'Source availability and compatibility.',
        order: 6,
        enabled: true,
        required: true,
        severity: ReleaseEvidenceCollectionRuleSeverity.blocking,
        aggregationMode: ReleaseEvidenceRuleSetAggregationMode.all,
        ruleIds: ['RE007', 'RE008', 'RE018'],
        rationale: 'All required sources must be available and compatible.',
      ),
      ReleaseEvidenceCollectionRuleSet(
        ruleSetId: 'verification-readiness',
        name: 'Verification readiness',
        description: 'Schema and policy compatibility for verification.',
        order: 7,
        enabled: true,
        required: true,
        severity: ReleaseEvidenceCollectionRuleSeverity.critical,
        aggregationMode: ReleaseEvidenceRuleSetAggregationMode.all,
        ruleIds: ['RE022'],
        rationale: 'Bundle must be verification-ready.',
      ),
    ];
  }

  static ReleaseEvidenceCollectionRule _rule({
    required String ruleId,
    required String ruleSetId,
    required String name,
    required ReleaseEvidenceCollectionRuleTarget target,
    required ReleaseEvidenceCollectionRuleOperator operator,
    ReleaseEvidenceRuleValue? expected,
    ReleaseEvidenceCollectionRuleSelector selector =
        const ReleaseEvidenceCollectionRuleSelector(),
    ReleaseEvidenceCollectionRuleSeverity severity =
        ReleaseEvidenceCollectionRuleSeverity.blocking,
    ReleaseEvidenceCollectionRuleRequirement requirement =
        ReleaseEvidenceCollectionRuleRequirement.required,
    int order = 0,
  }) {
    return ReleaseEvidenceCollectionRule(
      ruleId: ruleId,
      ruleSetId: ruleSetId,
      name: name,
      description: name,
      target: target,
      selector: selector,
      operator: operator,
      expectedValue: expected,
      severity: severity,
      requirement: requirement,
      missingDataPolicy: ReleaseEvidenceMissingDataPolicy.fail,
      incompatibleDataPolicy: ReleaseEvidenceIncompatibleDataPolicy.fail,
      evidenceRole: ReleaseEvidenceRole.normative,
      rationale: 'Candidate v1 rule $ruleId',
      order: order,
    );
  }
}
