/** Reason codes estáveis para monitor/reconciliation. */

export const ReasonCode = Object.freeze({
  APPROVED_NOT_GRANTED: "APPROVED_NOT_GRANTED",
  ALREADY_GRANTED: "ALREADY_GRANTED",
  MAPPING_AMBIGUOUS: "MAPPING_AMBIGUOUS",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  PLAN_UNKNOWN: "PLAN_UNKNOWN",
  ZERO_AMOUNT: "ZERO_AMOUNT",
  PAYMENT_REFUNDED: "PAYMENT_REFUNDED",
  PAYMENT_CHARGEDBACK: "PAYMENT_CHARGEDBACK",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_NOT_ELIGIBLE: "PAYMENT_NOT_ELIGIBLE",
  PERIOD_EXPIRED: "PERIOD_EXPIRED",
  PERIOD_UNKNOWN: "PERIOD_UNKNOWN",
  OVERLAPPING_ENTITLEMENT: "OVERLAPPING_ENTITLEMENT",
  PROCESSING_NOT_STALE: "PROCESSING_NOT_STALE",
  UNRELATED_PAYMENT: "UNRELATED_PAYMENT",
  ALREADY_RECONCILED: "ALREADY_RECONCILED",
  GRANT_RACE_LOST: "GRANT_RACE_LOST",
});

export const Classification = Object.freeze({
  IN_FLIGHT: "IN_FLIGHT",
  STALE_PROVIDER_APPROVED: "STALE_PROVIDER_APPROVED",
  STALE_PROVIDER_PENDING: "STALE_PROVIDER_PENDING",
  PROVIDER_REJECTED: "PROVIDER_REJECTED",
  PROVIDER_REFUNDED: "PROVIDER_REFUNDED",
  PROVIDER_CHARGEDBACK: "PROVIDER_CHARGEDBACK",
  PROVIDER_NOT_FOUND: "PROVIDER_NOT_FOUND",
  MAPPING_FAILURE: "MAPPING_FAILURE",
  ALREADY_GRANTED: "ALREADY_GRANTED",
  MANUAL_REVIEW_REQUIRED: "MANUAL_REVIEW_REQUIRED",
  SAFE_REPAIR_CANDIDATE: "SAFE_REPAIR_CANDIDATE",
  BUSINESS_DECISION_REQUIRED: "BUSINESS_DECISION_REQUIRED",
  UNRELATED_PAYMENT: "UNRELATED_PAYMENT",
  PROVIDER_NOT_ELIGIBLE: "PROVIDER_NOT_ELIGIBLE",
});

export const ReconciliationOutcome = Object.freeze({
  SAFE_REPAIR_CANDIDATE: "SAFE_REPAIR_CANDIDATE",
  ALREADY_GRANTED: "ALREADY_GRANTED",
  IN_FLIGHT: "IN_FLIGHT",
  BUSINESS_DECISION_REQUIRED: "BUSINESS_DECISION_REQUIRED",
  MAPPING_FAILURE: "MAPPING_FAILURE",
  PROVIDER_NOT_ELIGIBLE: "PROVIDER_NOT_ELIGIBLE",
  UNRELATED_PAYMENT: "UNRELATED_PAYMENT",
  MANUAL_REVIEW_REQUIRED: "MANUAL_REVIEW_REQUIRED",
  ALREADY_RECONCILED: "ALREADY_RECONCILED",
  REPAIR_APPLIED: "REPAIR_APPLIED",
  REPAIR_SKIPPED_DRY_RUN: "REPAIR_SKIPPED_DRY_RUN",
});
